- hosts: all
  become: yes
  vars:
    mysql_root_pass: wordpress

  tasks:

  - name: Install common packages
    apt: name={{ item }} state=latest
    with_items:
      - build-essential

  # Apache2

  - name: Ensure apache is installed
    apt: pkg=apache2 state=latest
  - name: Make sure apache is running
    action: service name=apache2 state=started enabled=true

  # MySQL

  - name: Set MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_pass | quote}}' vtype='password'
  - name: Confirm MySQL root password before installing
    debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_pass | quote}}' vtype='password'
  - name: Install MySQL
    apt: pkg=mysql-server state=latest
  - name: Make sure MySQL is running
    action: service name=mysql state=started enabled=true

  # PHP

  - name: Install PHP packages
    apt: name={{ item }} state=latest
    with_items:
      - php
      - libapache2-mod-php
      - php-cli
      - php-dev
      - php-mbstring
      - php-mysql
      - php-gd
      - php-curl
      - php-xdebug
      - phpunit
      - composer
    notify: restart apache

  # Ruby
  - name: Install Ruby
    apt: pkg=ruby state=latest

  # Node.js
  - name: Download Node.js PPM
    get_url:
      url=https://deb.nodesource.com/setup_6.x dest=/tmp/setup.sh mode=0440
  - name: Install Node.js PPM
    shell: bash /tmp/setup.sh
  - name: Install Node.js
    apt: name=nodejs state=latest

  # SSH
  - name: Create ~/.ssh directory
    file: path=/home/ubuntu/.ssh state=directory owner=ubuntu group=ubuntu mode=0700
  - name: Download the insecure key for vagrant user
    get_url: url=https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant.pub dest=/home/ubuntu/.ssh/authorized_keys force=yes

  # SSHD
  - name: disable sshd password auth
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication yes" line="PasswordAuthentication no"

  # Optimization
  - shell: bash /vagrant/clear.sh

  handlers:
    - name: restart apache
      action: service name=apache2 state=restarted
    - name: restart mysql
      action: service name=mysql state=restarted
